Galerkin Discretization Library with GridTools: gdl::assembly_base< Geometry > Struct Template Reference
gdl::assembly_base< Geometry > Struct Template Reference
#include <assembly_base.hpp>
Public Types
using geo_map = typename Geometry::geo_map
using geometry_t = Geometry
using grid_type = storage_t< grid_type_info >
using grid_type_info = storage_info< __COUNTER__, layout_tt< 5 > >
Public Member Functions
assembly_base (uint_t d1, uint_t d2, uint_t d3)
grid_type const & get_grid () const
grid_type_info const & get_grid_info () const
grid_type & grid ()
Data Fields
uint_t m_d1
uint_t m_d2
uint_t m_d3
Private Attributes
grid_type m_grid
grid_type_info m_grid_info
Member Typedef Documentation
template<typename Geometry> using gdl::assembly_base< Geometry >::geo_map = typename Geometry::geo_map
template<typename Geometry> using gdl::assembly_base< Geometry >::geometry_t = Geometry
template<typename Geometry> using gdl::assembly_base< Geometry >::grid_type = storage_t< grid_type_info >
template<typename Geometry> using gdl::assembly_base< Geometry >::grid_type_info = storage_info< __COUNTER__, layout_tt<5> >
Constructor & Destructor Documentation
template<typename Geometry> gdl::assembly_base< Geometry >::assembly_base (uint_t d1, uint_t d2, uint_t d3) inline
Member Function Documentation
template<typename Geometry> grid_type const& gdl::assembly_base< Geometry >::get_grid () const inline
Referenced by legendre::legendre_advection::grid(), gdl::intrepid::test(), and gdl::intrepid::test_mass().
template<typename Geometry> grid_type_info const& gdl::assembly_base< Geometry >::get_grid_info () const inline
template<typename Geometry> grid_type& gdl::assembly_base< Geometry >::grid () inline
Referenced by gdl::aggregator_type_tuple< assembly_base< Geometry >, Rest... >::domain(), gdl::assembly_cg< Geo >::grid(), legendre::legendre_advection::grid(), and gdl::assembly_cg< Geo >::release().
Field Documentation
template<typename Geometry> uint_t gdl::assembly_base< Geometry >::m_d1
template<typename Geometry> uint_t gdl::assembly_base< Geometry >::m_d2
template<typename Geometry> uint_t gdl::assembly_base< Geometry >::m_d3
template<typename Geometry> grid_type gdl::assembly_base< Geometry >::m_grid private
Referenced by gdl::assembly_base< Geo >::get_grid(), and gdl::assembly_base< Geo >::grid().
template<typename Geometry> grid_type_info gdl::assembly_base< Geometry >::m_grid_info private
Referenced by gdl::assembly_base< Geo >::get_grid_info().
The documentation for this struct was generated from the following file:
/Users/bignamic/Development/Galerking4GT/galerkin4gt/numerics/assembly_base.hpp