Galerkin Discretization Library with GridTools: gdl::assembly_dg< Geo > Struct Template Reference
gdl::assembly_dg< Geo > Struct Template Reference
#include <assembly_dg.hpp>
Public Types
using as_base_t = assembly_base< Geo >
using as_bd_t = bd_assembly< bd_discr_t >
using as_t = assembly< Geo >
using bd_cub_t = intrepid::boundary_cub< geo_map_t, cub_t::cubDegree >
using bd_cub_weights_t = typename as_bd_t::bd_cub_weights_t
using bd_discr_t = intrepid::boundary_discr< bd_cub_t >
using bd_dphi_t = typename as_bd_t::dphi_t
using bd_jacobian_t = typename as_bd_t::jacobian_type
using bd_measure_t = typename as_bd_t::storage_type
using bd_phi_t = typename as_bd_t::phi_t
using boundary_t = as_bd_t
using cub_t = typename super::cub_t
using dphi_t = typename as_t::dphi_t
using face_normals_t = typename as_bd_t::face_normals_type
using geo_map_t = typename super::geo_map_t
using geometry_t = Geo
using grid_type = typename super::grid_type
using jacobian_t = typename as_t::jacobian_type
using phi_t = typename as_t::phi_t
using storage_type = typename as_t::storage_type
using super = assembly_cg< Geo >
using tangent_storage_t = typename as_bd_t::tangent_storage_t
using weights_storage_t = typename as_t::weights_storage_t
Public Member Functions
assembly_dg (uint_t d1_, uint_t d2_, uint_t d3_)
bd_cub_weights_t & bd_cub_weights ()
bd_dphi_t & bd_dphi ()
bd_jacobian_t & bd_jac ()
bd_measure_t & bd_measure ()
bd_phi_t & bd_phi ()
void compute (Intrepid::EOperator op)
weights_storage_t & cub_weights ()
dphi_t & dphi ()
Geo & geo ()
grid_type & grid ()
jacobian_t & jac ()
storage_type & jac_det ()
jacobian_t & jac_inv ()
face_normals_t & normals ()
phi_t & phi ()
tangent_storage_t & ref_normals ()
void release ()
Protected Attributes
as_t m_as
as_base_t m_as_base
Geo m_geo
bool m_valid
Private Attributes
as_bd_t m_as_bd
bd_cub_t m_bd_cub
bd_discr_t m_bd_discr
Member Typedef Documentation
template<typename Geo > using gdl::assembly_cg< Geo >::as_base_t = assembly_base<Geo> inherited
template<typename Geo > using gdl::assembly_dg< Geo >::as_bd_t = bd_assembly<bd_discr_t>
template<typename Geo > using gdl::assembly_cg< Geo >::as_t = assembly<Geo> inherited
template<typename Geo > using gdl::assembly_dg< Geo >::bd_cub_t = intrepid::boundary_cub<geo_map_t, cub_t::cubDegree>
template<typename Geo > using gdl::assembly_dg< Geo >::bd_cub_weights_t = typename as_bd_t::bd_cub_weights_t
template<typename Geo > using gdl::assembly_dg< Geo >::bd_discr_t = intrepid::boundary_discr<bd_cub_t>
template<typename Geo > using gdl::assembly_dg< Geo >::bd_dphi_t = typename as_bd_t::dphi_t
template<typename Geo > using gdl::assembly_dg< Geo >::bd_jacobian_t = typename as_bd_t::jacobian_type
template<typename Geo > using gdl::assembly_dg< Geo >::bd_measure_t = typename as_bd_t::storage_type
template<typename Geo > using gdl::assembly_dg< Geo >::bd_phi_t = typename as_bd_t::phi_t
template<typename Geo > using gdl::assembly_dg< Geo >::boundary_t = as_bd_t
template<typename Geo > using gdl::assembly_dg< Geo >::cub_t = typename super::cub_t
template<typename Geo > using gdl::assembly_cg< Geo >::dphi_t = typename as_t::dphi_t inherited
template<typename Geo > using gdl::assembly_dg< Geo >::face_normals_t = typename as_bd_t::face_normals_type
template<typename Geo > using gdl::assembly_dg< Geo >::geo_map_t = typename super::geo_map_t
template<typename Geo > using gdl::assembly_cg< Geo >::geometry_t = Geo inherited
template<typename Geo > using gdl::assembly_dg< Geo >::grid_type = typename super::grid_type
template<typename Geo > using gdl::assembly_cg< Geo >::jacobian_t = typename as_t::jacobian_type inherited
template<typename Geo > using gdl::assembly_cg< Geo >::phi_t = typename as_t::phi_t inherited
template<typename Geo > using gdl::assembly_cg< Geo >::storage_type = typename as_t::storage_type inherited
template<typename Geo > using gdl::assembly_dg< Geo >::super = assembly_cg<Geo>
template<typename Geo > using gdl::assembly_dg< Geo >::tangent_storage_t = typename as_bd_t::tangent_storage_t
template<typename Geo > using gdl::assembly_cg< Geo >::weights_storage_t = typename as_t::weights_storage_t inherited
Constructor & Destructor Documentation
template<typename Geo > gdl::assembly_dg< Geo >::assembly_dg (uint_t d1_, uint_t d2_, uint_t d3_) inline
Member Function Documentation
template<typename Geo > bd_cub_weights_t& gdl::assembly_dg< Geo >::bd_cub_weights () inline
References gdl::bd_assembly< Boundary >::bd_backend(), gdl::intrepid::boundary_discr< Rule, Boundaries >::bd_cub_weights(), and gdl::assembly_cg< Geo >::m_valid.
template<typename Geo > bd_dphi_t& gdl::assembly_dg< Geo >::bd_dphi () inline
References gdl::bd_assembly< Boundary >::bd_backend(), gdl::intrepid::boundary_discr< Rule, Boundaries >::grad(), and gdl::assembly_cg< Geo >::m_valid.
template<typename Geo > bd_jacobian_t& gdl::assembly_dg< Geo >::bd_jac () inline
References gdl::bd_assembly< Boundary >::bd_jac(), and gdl::assembly_cg< Geo >::m_valid.
template<typename Geo > bd_measure_t& gdl::assembly_dg< Geo >::bd_measure () inline
References gdl::bd_assembly< Boundary >::bd_measure(), and gdl::assembly_cg< Geo >::m_valid.
template<typename Geo > bd_phi_t& gdl::assembly_dg< Geo >::bd_phi () inline
References gdl::bd_assembly< Boundary >::bd_backend(), gdl::assembly_cg< Geo >::m_valid, and gdl::intrepid::boundary_discr< Rule, Boundaries >::val().
template<typename Geo > void gdl::assembly_dg< Geo >::compute (Intrepid::EOperator op) inline
References gdl::assembly_cg< Geo >::compute(), gdl::intrepid::boundary_discr< Rule, Boundaries >::compute(), and gdl::assembly_cg< Geo >::m_geo.
template<typename Geo > weights_storage_t& gdl::assembly_cg< Geo >::cub_weights () inline inherited
References gdl::assembly< Geometry >::cub_weights().
template<typename Geo > dphi_t& gdl::assembly_cg< Geo >::dphi () inline inherited
References gdl::assembly< Geometry >::fe_backend().
template<typename Geo > Geo& gdl::assembly_cg< Geo >::geo () inline inherited
References gdl::assembly_cg< Geo >::m_geo.
template<typename Geo > grid_type& gdl::assembly_cg< Geo >::grid () inline inherited
References gdl::assembly_base< Geometry >::grid().
template<typename Geo > jacobian_t& gdl::assembly_cg< Geo >::jac () inline inherited
References gdl::assembly< Geometry >::jac().
template<typename Geo > storage_type& gdl::assembly_cg< Geo >::jac_det () inline inherited
References gdl::assembly< Geometry >::jac_det().
template<typename Geo > jacobian_t& gdl::assembly_cg< Geo >::jac_inv () inline inherited
References gdl::assembly< Geometry >::jac_inv().
template<typename Geo > face_normals_t& gdl::assembly_dg< Geo >::normals () inline
References gdl::assembly_cg< Geo >::m_valid, and gdl::bd_assembly< Boundary >::normals().
template<typename Geo > phi_t& gdl::assembly_cg< Geo >::phi () inline inherited
References gdl::assembly< Geometry >::fe_backend().
template<typename Geo > tangent_storage_t& gdl::assembly_dg< Geo >::ref_normals () inline
References gdl::bd_assembly< Boundary >::bd_backend(), gdl::assembly_cg< Geo >::m_valid, and gdl::intrepid::boundary_discr< Rule, Boundaries >::ref_normals().
template<typename Geo > void gdl::assembly_dg< Geo >::release () inline
References gdl::bd_assembly< Boundary >::bd_backend(), gdl::intrepid::boundary_discr< Rule, Boundaries >::bd_cub_weights(), gdl::bd_assembly< Boundary >::bd_jac(), gdl::bd_assembly< Boundary >::bd_measure(), gdl::intrepid::boundary_discr< Rule, Boundaries >::grad(), gdl::bd_assembly< Boundary >::normals(), gdl::intrepid::boundary_discr< Rule, Boundaries >::ref_normals(), gdl::assembly_cg< Geo >::release(), and gdl::intrepid::boundary_discr< Rule, Boundaries >::val().
Field Documentation
template<typename Geo > as_t gdl::assembly_cg< Geo >::m_as protected inherited
template<typename Geo > as_base_t gdl::assembly_cg< Geo >::m_as_base protected inherited
template<typename Geo > as_bd_t gdl::assembly_dg< Geo >::m_as_bd private
template<typename Geo > bd_cub_t gdl::assembly_dg< Geo >::m_bd_cub private
template<typename Geo > bd_discr_t gdl::assembly_dg< Geo >::m_bd_discr private
template<typename Geo > Geo gdl::assembly_cg< Geo >::m_geo protected inherited
Referenced by gdl::assembly_dg< Geo >::compute(), and gdl::assembly_cg< Geo >::geo().
template<typename Geo > bool gdl::assembly_cg< Geo >::m_valid protected inherited
Referenced by gdl::assembly_dg< Geo >::bd_cub_weights(), gdl::assembly_dg< Geo >::bd_dphi(), gdl::assembly_dg< Geo >::bd_jac(), gdl::assembly_dg< Geo >::bd_measure(), gdl::assembly_dg< Geo >::bd_phi(), gdl::assembly_dg< Geo >::normals(), and gdl::assembly_dg< Geo >::ref_normals().
The documentation for this struct was generated from the following file:
/Users/bignamic/Development/Galerking4GT/galerkin4gt/numerics/assembly_dg.hpp