Galerkin Discretization Library with GridTools: gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 > Struct Template Reference
gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 > Struct Template Reference
#include <assemble_storage.hpp>
Public Types
using base_storage_type = typename storage_t< MetaData >::basic_type
using indexing_t = gt::meta_storage_base< static_int< __COUNTER__ >, gt::layout_map< 2, 1, 0 >, false >
using storage_metadata = MetaData
Public Member Functions
template<typename... ExtraArgs >
assemble_storage (const MetaData *i_storage_info, const halo_data &i_halo_data, ExtraArgs const &...i_args)
constructor
GT_FUNCTION float_type get_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1, ushort_t i_Id2, ushort_t i_Jd2, ushort_t i_Kd2)
global dof base data access method
float_type get_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1)
GT_FUNCTION float_type get_value (uint_t i_I, uint_t i_J)
global dof base data access method
float_type get_value (uint_t i_I)
GRIDTOOLS_STATIC_ASSERT ((BasisCardinality0==BasisCardinality1),"GDL Error: basis cardinality in first and second direction must be the same")
GRIDTOOLS_STATIC_ASSERT ((BasisCardinality0==BasisCardinality2),"GDL Error: basis cardinality in first and second direction must be the same")
float_type & set_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1, ushort_t i_Id2, ushort_t i_Jd2, ushort_t i_Kd2)
float_type & set_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1)
float_type & set_value (uint_t i_I, uint_t i_J)
float_type & set_value (uint_t i_I)
Private Attributes
const halo_data m_halo_data
const indexing_t m_indexing
const global_to_local_dof_translator< BasisCardinality0, BasisCardinality1, BasisCardinality2 > m_local_dof
const uint_t s_max_dof_1
const uint_t s_max_dof_2
Member Typedef Documentation
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> using gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::base_storage_type = typename storage_t< MetaData >::basic_type
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> using gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::indexing_t = gt::meta_storage_base<static_int<__COUNTER__>,gt::layout_map<2,1,0>,false>
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> using gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::storage_metadata = MetaData
Constructor & Destructor Documentation
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> template<typename... ExtraArgs > gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::assemble_storage (const MetaData * i_storage_info, const halo_data & i_halo_data, ExtraArgs const &... i_args) inline
constructor
Input and template parameters correspond to those expected by storage_t constructor
Member Function Documentation
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> GT_FUNCTION float_type gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::get_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1, ushort_t i_Id2, ushort_t i_Jd2, ushort_t i_Kd2) inline
global dof base data access method
Parameters
first dof global coord in x direction
first dof global coord in y direction
first dof global coord in z direction
second dof global coord in x direction
second dof global coord in y direction
second dof global coord in z direction
Returns
assemble matrix value for the provided dof coords
References gdl::global_to_local_dof_translator< BasisCardinality0, BasisCardinality1, BasisCardinality2 >::apply().
Referenced by gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::get_value().
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> float_type gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::get_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1) inline
References gdl::global_to_local_dof_translator< BasisCardinality0, BasisCardinality1, BasisCardinality2 >::apply().
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> GT_FUNCTION float_type gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::get_value (uint_t i_I, uint_t i_J) inline
global dof base data access method
Parameters
first dof
second dof
Returns
assemble matrix value for the provided global dof pair
References gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::get_value().
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> float_type gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::get_value (uint_t i_I) inline
References gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::get_value().
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::GRIDTOOLS_STATIC_ASSERT ((BasisCardinality0==BasisCardinality1) , "GDL Error: basis cardinality in first and second direction must be the same")
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::GRIDTOOLS_STATIC_ASSERT ((BasisCardinality0==BasisCardinality2) , "GDL Error: basis cardinality in first and second direction must be the same")
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> float_type& gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::set_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1, ushort_t i_Id2, ushort_t i_Jd2, ushort_t i_Kd2) inline
References gdl::global_to_local_dof_translator< BasisCardinality0, BasisCardinality1, BasisCardinality2 >::apply().
Referenced by gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::set_value().
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> float_type& gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::set_value (ushort_t i_Id1, ushort_t i_Jd1, ushort_t i_Kd1) inline
References gdl::global_to_local_dof_translator< BasisCardinality0, BasisCardinality1, BasisCardinality2 >::apply().
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> float_type& gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::set_value (uint_t i_I, uint_t i_J) inline
References gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::set_value().
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> float_type& gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::set_value (uint_t i_I) inline
References gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::set_value().
Field Documentation
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> const halo_data gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::m_halo_data private
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> const indexing_t gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::m_indexing private
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> const global_to_local_dof_translator<BasisCardinality0,BasisCardinality1,BasisCardinality2> gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::m_local_dof private
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> const uint_t gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::s_max_dof_1 private
template<typename MetaData , ushort_t BasisCardinality0, ushort_t BasisCardinality1 = BasisCardinality0, ushort_t BasisCardinality2 = BasisCardinality0> const uint_t gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >::s_max_dof_2 private
The documentation for this struct was generated from the following file:
/Users/bignamic/Development/Galerking4GT/galerkin4gt/numerics/assemble_storage.hpp