Galerkin Discretization Library with GridTools: /Users/bignamic/Development/Galerking4GT/galerkin4gt/examples/legendre/main.cpp File Reference
main.cpp File Reference
#include "legendre.hpp"
#include "boundary.hpp"
#include "compute_jacobian.hpp"
#include "compute_assembly.hpp"
#include "../../tools/io.hpp"
Data Structures
struct gdl::bc_functor
Namespaces
gdl
[assembly]
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References legendre::compute_jacobian::assemble(), legendre::compute_assembly::assemble(), legendre::legendre_advection::assembler(), legendre::legendre_advection::bd_assembler(), gdl::bd_assembly< Boundary >::bd_backend(), legendre::legendre_advection::bd_beta_n(), gdl::bd_assembly< Boundary >::bd_jac(), legendre::legendre_advection::bd_mass(), legendre::legendre_advection::bd_mass_uv(), legendre::legendre_advection::beta_phys(), gdl::intrepid::discretization< FE, Cub >::cub_weights(), d1, d2, d3, legendre::legendre_advection::eval(), legendre::legendre_advection::fe(), gdl::assembly< Geometry >::fe_backend(), legendre::legendre_advection::finalize(), gdl::assembly< Geometry >::jac(), gdl::assembly< Geometry >::jac_det(), gdl::assembly< Geometry >::jac_inv(), gdl::bd_assembly< Boundary >::normals(), legendre::legendre_advection::normals(), gdl::intrepid::boundary_discr< Rule, Boundaries >::ref_normals(), legendre::legendre_advection::result(), legendre::legendre_advection::run(), and gdl::intrepid::discretization< FE, Cub >::val().