Galerkin Discretization Library with GridTools: /Users/bignamic/Development/Galerking4GT/galerkin4gt/playground/IGA/RunTimeIGA/b_splines_surface_eval_test_rt.cpp File Reference
b_splines_surface_eval_test_rt.cpp File Reference
#include "b_splines_surface_rt.h"
#include "point.h"
#include <iostream>
#include <boost/mpl/vector.hpp>
#include <boost/shared_ptr.hpp>
#include <stencil-composition/stencil-composition.hpp>
Data Structures
struct curve_struct
Macros
#define BACKEND backend<gridtools::enumtype::Host, gridtools::enumtype::GRIDBACKEND, gridtools::enumtype::Naive>
Typedefs
typedef interval< level< 0,-1 >, level< 1, 1 > > third_axis
typedef interval< level< 0,-1 >, level< 1,-1 > > x_lap
Functions
std::vector< iga_rt::Point< D > > control_points (N)
iga_rt::BSplineCurve< P, N, D > curve (knots, control_points)
constexpr int D (2)
int main ()
constexpr int N (7)
constexpr int NK (P+N+1)
constexpr int P (2)
Variables
constexpr std::array< double, NK > knots {0,0,0,1,2,3,4,5,5,5}
Macro Definition Documentation
#define BACKEND backend<gridtools::enumtype::Host, gridtools::enumtype::GRIDBACKEND, gridtools::enumtype::Naive>
Typedef Documentation
typedef interval<level<0,-1>, level<1,1> > third_axis
typedef interval<level<0,-1>, level<1,-1> > x_lap
Function Documentation
std::vector<iga_rt::Point<D> > control_points (N)
Referenced by main().
iga_rt::BSplineCurve<P,N,D> curve (knots , control_points)
Referenced by curve_struct::Do(), and main().
constexpr int D (2)
Referenced by curve_struct::Do(), gdl::functors::lax_friedrich< Geometry, Flux >::Do(), gdl::intrepid::geometry< geo_map, cub >::geometry(), and main().
int main ()
References control_points(), curve(), D(), and N().
constexpr int N (7)
Referenced by main().
constexpr int NK (P+N+ 1)
constexpr int P (2)
Variable Documentation
constexpr std::array<double, NK> knots {0,0,0,1,2,3,4,5,5,5}