Galerkin Discretization Library with GridTools: /Users/bignamic/Development/Galerking4GT/galerkin4gt/mesh/bc_tags_handling.hpp File Reference
bc_tags_handling.hpp File Reference
#include <tuple>
#include <boost/fusion/algorithm/iteration/for_each.hpp>
#include <boost/fusion/adapted/std_tuple.hpp>
Data Structures
struct bc_tag_assigner< FirstSubdomainDef, OtherSubdomainDefs... >
struct bc_tag_assigner_static
struct coord_t
struct segment
struct square
struct subdomain< SubdomainDef >
struct subdomain_data< SubdomainDef >
struct subdomain_geom_data< SubdomainDef >
struct subdomain_geom_data< segment >
struct subdomain_geom_data< square >
struct tag_assigner_operator
struct tagged_subdomain< SubdomainDef >
struct tagged_subdomain_data< SubdomainDef >
Functions
double mod (const coord_t &i_coord)
double mod2 (const coord_t &i_coord)
double operator* (const coord_t &i_point1, const coord_t &i_point2)
coord_t operator- (const coord_t &i_point1, const coord_t &i_point2)
coord_t operator^ (const coord_t &i_point1, const coord_t &i_point2)
Function Documentation
double mod (const coord_t & i_coord) inline
References coord_t::mod().
double mod2 (const coord_t & i_coord) inline
References coord_t::mod2().
Referenced by segment::is_on_boundary_impl().
double operator* (const coord_t & i_point1, const coord_t & i_point2)
References coord_t::x(), coord_t::y(), and coord_t::z().
coord_t operator- (const coord_t & i_point1, const coord_t & i_point2)
References coord_t::x(), coord_t::y(), and coord_t::z().
coord_t operator^ (const coord_t & i_point1, const coord_t & i_point2)
References coord_t::x(), coord_t::y(), and coord_t::z().