Galerkin4GT: /Users/bignamic/Development/Galerking4GT/galerkin4gt/tools/io.hpp File Reference
io.hpp File Reference
#include <cstring>
#include <XdmfReader.hpp>
#include <XdmfWriter.hpp>
#include <XdmfDomain.hpp>
#include <XdmfRectilinearGrid.hpp>
#include <XdmfRegularGrid.hpp>
#include <XdmfHDF5Writer.hpp>
#include <XdmfArray.hpp>
#include <XdmfAttribute.hpp>
#include <XdmfAttributeCenter.hpp>
#include <XdmfAttributeType.hpp>
#include <XdmfArrayType.hpp>
#include <XdmfHDF5Controller.hpp>
#include <XdmfInformation.hpp>
#include <XdmfTime.hpp>
#include <gridtools.hpp>
#include <iostream>
#include <fstream>
#include <common/defs.hpp>
#include "../galerkin_defs.hpp"
Data Structures
struct gdl::create_grid< io_grid_type >
struct gdl::create_grid< enumtype::rectilinear >
struct gdl::create_grid< enumtype::regular >
creates a regular grid
struct gdl::io_base< Derived >
struct gdl::io_base< Derived< Storage, Args ... > >
struct gdl::io_rectilinear< Storage >
I/O class for rectilinear grids, i.e. structured grid with elements of different sizes.
struct gdl::io_rectilinear< Storage, LocalGrid >
struct gdl::io_regular< Storage >
struct gdl::io_regular< Storage >
Functions
template<typename Storage , typename LocalGridInfo >
void gdl::reindex (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
Performing a copy of a scalar field into the provided data pointer.
template<ushort_t Face, typename Storage , typename LocalGridInfo >
void gdl::reindex_on_face (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
template<ushort_t CubDegree, typename Storage >
void gdl::reindex_on_qpoints (Storage const &storage_, typename Storage::value_type *data_)
template<typename Storage , typename LocalGridInfo >
void gdl::reindex_vec (Storage const &storage_, LocalGridInfo const &local_grid_info_, typename Storage::value_type *data_)
function to serialize the scalar/vector valued fields living on a mesh into an array
template<typename Storage >
void gdl::spy (Storage const &storage_, char const *name)
export a matrix in matrix market format
template<typename Storage >
void gdl::spy_vec (Storage const &storage_, char const *name)
exports a vector
Function Documentation
reindex()
template<typename Storage , typename LocalGridInfo > void gdl::reindex (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
Performing a copy of a scalar field into the provided data pointer.
Note
unsafe
References gdl::reindex().
Referenced by gdl::reindex(), and gdl::io_rectilinear< Storage, LocalGrid >::set_attribute_scalar().
reindex_on_face()
template<ushort_t Face, typename Storage , typename LocalGridInfo > void gdl::reindex_on_face (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
Performing a copy of all the dofs on faces 0, 2 ,4, in order to fix the memory layout
References gdl::reindex_on_face().
Referenced by gdl::reindex_on_face().
reindex_on_qpoints()
template<ushort_t CubDegree, typename Storage > void gdl::reindex_on_qpoints (Storage const & storage_, typename Storage::value_type * data_)
Performing a copy of all the quadrature points, in order to fix the memory layout
References gdl::reindex_on_qpoints().
Referenced by gdl::reindex_on_qpoints().
reindex_vec()
template<typename Storage , typename LocalGridInfo > void gdl::reindex_vec (Storage const & storage_, LocalGridInfo const & local_grid_info_, typename Storage::value_type * data_)
function to serialize the scalar/vector valued fields living on a mesh into an array
This is needed in order to write the vector to the output file
References gdl::reindex_vec().
Referenced by gdl::reindex_vec(), and gdl::io_rectilinear< Storage, LocalGrid >::set_attribute_vector().
spy()
template<typename Storage > void gdl::spy (Storage const & storage_, char const * name)
export a matrix in matrix market format
This function writes a matrix to a text file in matrix market format. This format can be loaded by Matlab/Octave to see the matrix pattern, and it is a specific format for sparse matrices. It consists of lines with 3 entries: the first 2 for the i,j coordinates, and the third for the nonzero matrix value.
Examples:
dg_advection.cpp, dg_flux.cpp, and mass.cpp.
References gdl::spy().
Referenced by gdl::spy().
spy_vec()
template<typename Storage > void gdl::spy_vec (Storage const & storage_, char const * name)
exports a vector
this function writes out a vector in text format, in a newline-separated list which can be loaded (e.g.) by Matlab/Octave
Examples:
dg_advection.cpp.
References gdl::spy_vec().
Referenced by gdl::spy_vec().