var hierarchy =
[
    [ "gdl::functors::advection< Geo, Cubature >", "a37461.html", null ],
    [ "gdl::aggregator_type_tuple< assembly< Geometry >, Rest ... >::advection< FE, Cubature >", "a37785.html", null ],
    [ "gdl::aggregator_type_tuple< Types >", "a37793.html", null ],
    [ "gdl::aggregator_type_tuple< Rest ... >", "a37793.html", [
      [ "gdl::aggregator_type_tuple< assembly< Geometry >, Rest ... >", "a37769.html", null ],
      [ "gdl::aggregator_type_tuple< assembly_base< Geometry >, Rest ... >", "a37801.html", null ],
      [ "gdl::aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >", "a37833.html", null ]
    ] ],
    [ "gdl::aggregator_type_tuple<>", "a37797.html", null ],
    [ "gdl::functors::apply_dirichlet_boundary_conditions_bottom< N_DOF0, N_DOF1, N_DOF2, BoundaryFunctionDefinition >", "a37437.html", null ],
    [ "gdl::functors::apply_dirichlet_boundary_conditions_front< N_DOF0, N_DOF1, N_DOF2, BoundaryFunctionDefinition >", "a37449.html", null ],
    [ "gdl::functors::apply_dirichlet_boundary_conditions_left< N_DOF0, N_DOF1, N_DOF2, BoundaryFunctionDefinition >", "a37441.html", null ],
    [ "gdl::functors::apply_dirichlet_boundary_conditions_rear< N_DOF0, N_DOF1, N_DOF2, BoundaryFunctionDefinition >", "a37453.html", null ],
    [ "gdl::functors::apply_dirichlet_boundary_conditions_right< N_DOF0, N_DOF1, N_DOF2, BoundaryFunctionDefinition >", "a37445.html", null ],
    [ "gdl::functors::apply_dirichlet_boundary_conditions_top< N_DOF0, N_DOF1, N_DOF2, BoundaryFunctionDefinition >", "a37433.html", null ],
    [ "gdl::functors::assemble< Geometry >", "a37501.html", null ],
    [ "gdl::assembly< Geometry >", "a37765.html", null ],
    [ "gdl::assembly< Geo >", "a37765.html", null ],
    [ "gdl::assembly< geo_t >", "a37765.html", null ],
    [ "gdl::assembly_base< Geometry >", "a37789.html", null ],
    [ "gdl::assembly_base< Geo >", "a37789.html", null ],
    [ "gdl::assembly_base< geo_t >", "a37789.html", null ],
    [ "gdl::assembly_cg< Geo >", "a37805.html", [
      [ "gdl::assembly_dg< Geo >", "a37809.html", null ]
    ] ],
    [ "gdl::functors::assign< Dim, Value >", "a37525.html", null ],
    [ "gdl::functors::assign< 3, Value >", "a37529.html", null ],
    [ "gdl::functors::assign< 4, Value >", "a37533.html", null ],
    [ "gdl::functors::assign< 5, Value >", "a37537.html", null ],
    [ "gdl::parametric_space< order< P ... > >::assign_knots", "a38149.html", null ],
    [ "gdl::b_spline< Order >", "a38153.html", null ],
    [ "basic_type", null, [
      [ "gdl::assemble_storage< MetaData, BasisCardinality0, BasisCardinality1, BasisCardinality2 >", "a37741.html", null ]
    ] ],
    [ "gdl::basis_function< Id >", "a37369.html", null ],
    [ "gdl::basis_select< order, basis, shape >", "a37941.html", null ],
    [ "gdl::basis_select< 1, enumtype::Lagrange, enumtype::Hexa >", "a37957.html", null ],
    [ "gdl::basis_select< 1, enumtype::Lagrange, enumtype::Quad >", "a37977.html", null ],
    [ "gdl::basis_select< 1, enumtype::Lagrange, enumtype::Tetra >", "a37965.html", null ],
    [ "gdl::basis_select< 1, enumtype::Lagrange, enumtype::Tri >", "a37985.html", null ],
    [ "gdl::basis_select< order, enumtype::Lagrange, enumtype::Hexa >", "a37961.html", null ],
    [ "gdl::basis_select< order, enumtype::Lagrange, enumtype::Quad >", "a37973.html", null ],
    [ "gdl::basis_select< order, enumtype::Lagrange, enumtype::Tetra >", "a37969.html", null ],
    [ "gdl::basis_select< order, enumtype::Lagrange, enumtype::Tri >", "a37981.html", null ],
    [ "gdl::basis_select< P, enumtype::Legendre, enumtype::Hexa >", "a37945.html", null ],
    [ "gdl::basis_select< P, enumtype::Legendre, enumtype::Line >", "a37953.html", null ],
    [ "gdl::basis_select< P, enumtype::Legendre, enumtype::Quad >", "a37949.html", null ],
    [ "gdl::functors::bassi_rebay< Geometry >", "a37577.html", null ],
    [ "gdl::bc_apply< Assembler, Fe, BCFunctor, FluxFunctor >", "a37373.html", null ],
    [ "gdl::bc_functor", "a37385.html", null ],
    [ "bc_tag_assigner< FirstSubdomainDef, OtherSubdomainDefs >", "a37713.html", null ],
    [ "bc_tag_assigner_static", "a37717.html", null ],
    [ "gdl::bd_assembly< Boundary >", "a37829.html", null ],
    [ "gdl::bd_assembly< bd_discr_t >", "a37829.html", null ],
    [ "gdl::bd_assembly< bd_geo_t >", "a37829.html", null ],
    [ "gdl::aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >::bd_integrate", "a37841.html", null ],
    [ "gdl::functors::bd_integrate< BdGeometry >", "a37569.html", null ],
    [ "gdl::functors::bd_mass< FE, BoundaryCubature >", "a37545.html", null ],
    [ "gdl::functors::bd_mass_uv< FE, BoundaryCubature >", "a37549.html", null ],
    [ "gdl::functors::bd_mass_vu< FE, BoundaryCubature >", "a37553.html", null ],
    [ "gdl::functors::bd_transform< Face >", "a37601.html", null ],
    [ "gdl::intrepid::boundary_cub< GeoMap, Order >", "a38025.html", null ],
    [ "gdl::intrepid::boundary_cub< discr_map, cub::cubDegree >", "a38025.html", null ],
    [ "gdl::intrepid::boundary_cub< geo_map, cub::cubDegree >", "a38025.html", null ],
    [ "gdl::intrepid::boundary_cub< geo_map_t, cub_t::cubDegree >", "a38025.html", null ],
    [ "gdl::boundary_cubature< Cubature >", "a37937.html", null ],
    [ "gdl::intrepid::boundary_discr< Rule, Boundaries >", "a38029.html", null ],
    [ "gdl::intrepid::boundary_discr< bd_cub_t >", "a38029.html", null ],
    [ "gdl::intrepid::boundary_discr< bd_discr_cub_t >", "a38029.html", null ],
    [ "gdl::intrepid::boundary_discr< bd_geo_cub_t >", "a38029.html", null ],
    [ "gdl::boundary_shape< FE >", "a37989.html", null ],
    [ "BSpline", null, [
      [ "gdl::BSplineDerived< Coeff >", "a38117.html", null ]
    ] ],
    [ "bspline_basis_struct", "a38097.html", null ],
    [ "bspline_struct", "a38101.html", null ],
    [ "gdl::BSplineCoeff< Dim, Order, I >", "a38109.html", null ],
    [ "gdl::BSplineCoeff< Dim, order< P... >, I >", "a38113.html", null ],
    [ "gdl::cell< Order, ShapeType >", "a37885.html", null ],
    [ "gdl::combinations< n, m >", "a38073.html", null ],
    [ "legendre::compute_assembly", "a37393.html", null ],
    [ "gdl::functors::compute_face_normals< BdGeometry >", "a37565.html", null ],
    [ "gdl::aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >::compute_face_normals", "a37837.html", null ],
    [ "legendre::compute_jacobian", "a37397.html", null ],
    [ "coord_t", "a37669.html", null ],
    [ "gdl::functors::copy_vector< N_DOF >", "a37573.html", null ],
    [ "gdl::create_grid< io_grid_type >", "a38209.html", null ],
    [ "gdl::create_grid< enumtype::rectilinear >", "a38217.html", null ],
    [ "gdl::create_grid< enumtype::regular >", "a38213.html", null ],
    [ "gdl::create_layout< T >", "a37813.html", null ],
    [ "gdl::create_layout< gt::gt_integer_sequence< ushort_t, Id ... > >", "a37817.html", null ],
    [ "gdl::cubature< Order, CellType >", "a37933.html", null ],
    [ "gdl::functors::cubature_point_grid_generation< Geometry, S >", "a37413.html", null ],
    [ "curve_struct", "a38105.html", null ],
    [ "gdl::functors::det< Geometry >", "a37473.html", [
      [ "gdl::functors::det_impl< Geometry, 2 >", "a37481.html", null ],
      [ "gdl::functors::det_impl< Geometry, 3 >", "a37477.html", null ]
    ] ],
    [ "gdl::functors::det_impl< Geometry, Dim >", "a37469.html", null ],
    [ "gdl::intrepid::discretization< FE, Cub >", "a38013.html", null ],
    [ "gdl::intrepid::discretization< discr_map, cub >", "a38013.html", null ],
    [ "gdl::intrepid::discretization< geo_map, cub >", "a38013.html", [
      [ "gdl::intrepid::geometry< geo_map, cub >", "a38021.html", null ]
    ] ],
    [ "gdl::intrepid::discretization< GeoMap, Cubature >", "a38013.html", [
      [ "gdl::intrepid::geometry< GeoMap, Cubature >", "a38021.html", null ],
      [ "gdl::intrepid::unstructured_geometry< GeoMap, Cubature >", "a38017.html", null ]
    ] ],
    [ "dolfin_mesh", "a37721.html", null ],
    [ "gdl::functors::evaluate", "a37589.html", null ],
    [ "gdl::evaluate_polynomial< Dim, Order >", "a38033.html", null ],
    [ "gdl::evaluate_polynomial< 1, Order >", "a38045.html", null ],
    [ "gdl::evaluate_polynomial< 2, Order >", "a38041.html", null ],
    [ "gdl::evaluate_polynomial< 3, Order >", "a38037.html", null ],
    [ "gdl::factorial< N >", "a38065.html", null ],
    [ "gdl::factorial< 0 >", "a38069.html", null ],
    [ "false_", null, [
      [ "gridtools::is_temporary_storage< storage< ::gdl::assemble_storage< MetaData, Cardinalities ... > > >", "a37761.html", null ]
    ] ],
    [ "FE", "a38903.html", [
      [ "gdl::boundary_shape< FE< Order, BasisType, enumtype::Hexa > >", "a37993.html", null ],
      [ "gdl::boundary_shape< FE< Order, BasisType, enumtype::Line > >", "a38009.html", null ],
      [ "gdl::boundary_shape< FE< Order, BasisType, enumtype::Quad > >", "a38001.html", null ],
      [ "gdl::boundary_shape< FE< Order, BasisType, enumtype::Tetra > >", "a37997.html", null ],
      [ "gdl::boundary_shape< FE< Order, BasisType, enumtype::Tri > >", "a38005.html", null ]
    ] ],
    [ "float_value", "a37365.html", null ],
    [ "flux", "a37377.html", null ],
    [ "legendre::flux", "a37405.html", null ],
    [ "gdl::functors::function_evaluation< FunctionDefinition >", "a37417.html", null ],
    [ "functor", "a38241.html", null ],
    [ "functor", "a38241.html", null ],
    [ "gdl::b_spline< order< P... > >::functor_get_vals< ArrayKnots, Quad, Storage, Dims >::functor_assign_storage< Id, Basis, T >", "a38169.html", null ],
    [ "gdl::b_spline< order< P... > >::functor_get_vals< ArrayKnots, Quad, Storage, Dims >::functor_assign_storage< Id, Basis, gt::gt_integer_sequence< ushort_t, Integers... > >", "a38173.html", null ],
    [ "gdl::b_spline< order< P... > >::functor_get_vals< ArrayKnots, Quad, Storage, Dims >", "a38165.html", null ],
    [ "gdl::GenericBSpline< Coeff >", "a38129.html", null ],
    [ "gdl::b_spline< order< P... > >::functor_get_vals< ArrayKnots, Quad, Storage, Dims >::get_second< PP, NN >", "a38177.html", null ],
    [ "gdl::get_val< Tuple >", "a38121.html", null ],
    [ "gdl::functors::global_assemble", "a38085.html", null ],
    [ "gdl::functors::global_assemble_no_if", "a38089.html", null ],
    [ "gdl::global_to_local_dof_translator< BasisCardinality0, BasisCardinality1, BasisCardinality2 >", "a37737.html", null ],
    [ "gdl::functors::global_vector_assemble_no_if", "a38093.html", null ],
    [ "gdl::grid_adjacency_rule_applier< GridSpecificRuleApplier >", "a37725.html", null ],
    [ "gdl::grid_adjacency_rule_applier< hexa_grid_adjacency_rule_applier< BasisCardinality1D > >", "a37725.html", [
      [ "gdl::hexa_grid_adjacency_rule_applier< BasisCardinality1D >", "a37729.html", null ]
    ] ],
    [ "gdl::halo_data", "a37733.html", null ],
    [ "gdl::functors::hexahedron_assemble< N_DOF0, N_DOF1, N_DOF2 >", "a37509.html", null ],
    [ "gdl::functors::hexahedron_matrix_distribute< N_DOF0, N_DOF1, N_DOF2 >", "a37517.html", null ],
    [ "gdl::functors::hexahedron_vector_assemble< N_DOF0, N_DOF1, N_DOF2 >", "a37513.html", null ],
    [ "gdl::functors::hexahedron_vector_distribute< N_DOF0, N_DOF1, N_DOF2 >", "a37521.html", null ],
    [ "gdl::functors::inv< Geometry >", "a37489.html", [
      [ "gdl::functors::inv_impl< Geometry, 2 >", "a37497.html", null ],
      [ "gdl::functors::inv_impl< Geometry, 3 >", "a37493.html", null ]
    ] ],
    [ "gdl::functors::inv_impl< Geometry, Dim >", "a37485.html", null ],
    [ "gdl::io_base< Derived >", "a38201.html", null ],
    [ "gdl::io_base< Derived< Storage, Args ... > >", "a38205.html", null ],
    [ "gdl::io_base< io_rectilinear< Storage, LocalGrid > >", "a38201.html", [
      [ "gdl::io_rectilinear< Storage, LocalGrid >", "a38233.html", null ]
    ] ],
    [ "gdl::io_base< io_regular< Storage > >", "a38201.html", [
      [ "gdl::io_regular< Storage >", "a38225.html", null ]
    ] ],
    [ "gdl::io_rectilinear< Storage >", "a38229.html", null ],
    [ "gdl::io_regular< Storage >", "a38221.html", null ],
    [ "gdl::b_spline< order< P... > >::lambda_get_first< F, S >", "a38161.html", null ],
    [ "gdl::aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >::lax_friedrich< Flux >", "a37853.html", null ],
    [ "gdl::functors::lax_friedrich< Geometry, Flux >", "a37581.html", null ],
    [ "gdl::impl_::layout_from_dim< I >", "a37821.html", null ],
    [ "gdl::legendre< Dim, Order >", "a38049.html", null ],
    [ "legendre::legendre_advection", "a37409.html", null ],
    [ "linear", "a38249.html", null ],
    [ "gdl::linear_solver< Strategy >", "a38053.html", null ],
    [ "gdl::linear_solver< cg_solver< N_DOF0, N_DOF1, N_DOF2 > >", "a38053.html", [
      [ "gdl::cg_solver< N_DOF0, N_DOF1, N_DOF2 >", "a38057.html", null ]
    ] ],
    [ "functors::mass_IGA::mass< FE, Cubature >", "a38081.html", null ],
    [ "gdl::functors::mass", "a37605.html", null ],
    [ "gdl::aggregator_type_tuple< assembly< Geometry >, Rest ... >::mass< FE, Cubature >", "a37777.html", null ],
    [ "gdl::functors::matvec", "a37641.html", null ],
    [ "gdl::functors::matvec_BdxBdxBd", "a37649.html", null ],
    [ "gdl::functors::matvec_VolxBdxVol", "a37645.html", null ],
    [ "gdl::functors::measure< Geometry, Codimensoin >", "a37557.html", null ],
    [ "gdl::aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >::measure< Codimension >", "a37849.html", null ],
    [ "gdl::functors::measure< Geometry, 1 >", "a37561.html", null ],
    [ "legendre::mesh", "a37401.html", null ],
    [ "gdl::functors::mult_operator< T >", "a37617.html", null ],
    [ "gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Ranges >", "a38181.html", null ],
    [ "gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1 >", "a38185.html", null ],
    [ "gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range1, Range2, Range3 >", "a38189.html", null ],
    [ "gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, Range2, Range3 >", "a38193.html", null ],
    [ "gdl::nest_loop< ArrayKnots, Quad, Storage, InnerFunctor, static_int< I >, Range3 >", "a38197.html", null ],
    [ "gdl::shape_property< enumtype::Hexa >::normal< FaceOrd >", "a37905.html", null ],
    [ "gdl::functors::not_normalized_transform", "a37429.html", null ],
    [ "gdl::shape_property< enumtype::Hexa >::opposite< FaceOrd >", "a37909.html", null ],
    [ "gdl::order< P >", "a38061.html", null ],
    [ "gdl::pair_indexing< Size0, Size1, Size2 >", "a38237.html", null ],
    [ "gdl::parametric_space< Order >", "a38141.html", null ],
    [ "gdl::parametric_space< order< P ... > >", "a38145.html", null ],
    [ "gdl::parametric_space< order< P... > >", "a38141.html", [
      [ "gdl::b_spline< order< P... > >", "a38157.html", null ]
    ] ],
    [ "gdl::functors::partial_hexahedron_assembled_reduction< N_DOF0, N_DOF1, N_DOF2, Operator >", "a37657.html", null ],
    [ "gdl::functors::project_on_boundary", "a37653.html", null ],
    [ "gdl::functors::quadratic_boundary_value", "a37425.html", null ],
    [ "gdl::functors::quartic_source", "a37421.html", null ],
    [ "gdl::reference_element< Order, BasisType, ShapeType >", "a37825.html", null ],
    [ "gdl::residual", "a37381.html", null ],
    [ "gdl::get_val< Tuple >::result< T >", "a38125.html", null ],
    [ "gdl::GenericBSpline< Coeff >::multiplies_f::result< T >", "a38137.html", null ],
    [ "scalar", "a37457.html", null ],
    [ "gdl::functors::scalvec< Dim, Operator >", "a37621.html", null ],
    [ "gdl::functors::scalvec< 4, Operator >", "a37625.html", null ],
    [ "gdl::shape_property< S >", "a37889.html", null ],
    [ "gdl::shape_property< enumtype::Hexa >", "a37893.html", null ],
    [ "gdl::shape_property< enumtype::Line >", "a37925.html", null ],
    [ "gdl::shape_property< enumtype::Point >", "a37929.html", null ],
    [ "gdl::shape_property< enumtype::Quad >", "a37917.html", null ],
    [ "gdl::shape_property< enumtype::Tetra >", "a37913.html", null ],
    [ "gdl::shape_property< enumtype::Tri >", "a37921.html", null ],
    [ "gdl::shape_select< order, shape >", "a37861.html", null ],
    [ "gdl::shape_select< order, enumtype::Hexa >", "a37865.html", null ],
    [ "gdl::shape_select< order, enumtype::Line >", "a37881.html", null ],
    [ "gdl::shape_select< order, enumtype::Quad >", "a37873.html", null ],
    [ "gdl::shape_select< order, enumtype::Tetra >", "a37869.html", null ],
    [ "gdl::shape_select< order, enumtype::Tri >", "a37877.html", null ],
    [ "simple_gather< Geometry >", "a37389.html", null ],
    [ "gdl::aggregator_type_tuple< assembly< Geometry >, Rest ... >::stiffness< FE, Cubature >", "a37781.html", null ],
    [ "gdl::functors::stiffness< FE, Cubature >", "a37661.html", null ],
    [ "gdl::functors::sub_operator< T >", "a37613.html", null ],
    [ "subdomain< SubdomainDef >", "a37693.html", null ],
    [ "subdomain< segment >", "a37693.html", [
      [ "segment", "a37701.html", null ]
    ] ],
    [ "subdomain< square >", "a37693.html", [
      [ "square", "a37697.html", null ]
    ] ],
    [ "subdomain_data< SubdomainDef >", "a37685.html", null ],
    [ "subdomain_data< segment >", "a37685.html", null ],
    [ "subdomain_data< square >", "a37685.html", null ],
    [ "subdomain_geom_data< SubdomainDef >", "a37673.html", null ],
    [ "subdomain_geom_data< segment >", "a37681.html", null ],
    [ "subdomain_geom_data< square >", "a37677.html", null ],
    [ "gdl::functors::sum_operator< T >", "a37609.html", null ],
    [ "tag_assigned_operator", "a38245.html", null ],
    [ "tag_assigner_operator", "a37709.html", null ],
    [ "tagged_subdomain< SubdomainDef >", "a37705.html", null ],
    [ "tagged_subdomain_data< SubdomainDef >", "a37689.html", null ],
    [ "gdl::shape_property< enumtype::Hexa >::tangent_u< FaceOrd >", "a37897.html", null ],
    [ "gdl::shape_property< enumtype::Hexa >::tangent_v< FaceOrd >", "a37901.html", null ],
    [ "gdl::tensor_product_element< dimension, order >", "a38077.html", null ],
    [ "gdl::functors::transform", "a37593.html", null ],
    [ "gdl::functors::transform_vec", "a37597.html", null ],
    [ "true_", null, [
      [ "gridtools::is_actual_storage< pointer< ::gdl::assemble_storage< MetaData, Cardinalities ... > > >", "a37745.html", null ],
      [ "gridtools::is_any_iterate_domain_storage< ::gdl::assemble_storage< MetaData, Cardinalities ... > >", "a37749.html", null ],
      [ "gridtools::is_any_storage< ::gdl::assemble_storage< MetaData, Cardinalities ... > >", "a37753.html", null ],
      [ "gridtools::is_storage< ::gdl::assemble_storage< MetaData, Cardinalities ... > >", "a37757.html", null ]
    ] ],
    [ "gdl::functors::uniform< Geometry >", "a37505.html", null ],
    [ "gdl::functors::update_bd_jac< Geometry, S >", "a37541.html", null ],
    [ "gdl::aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >::update_bd_jac< S >", "a37845.html", null ],
    [ "gdl::aggregator_type_tuple< assembly< Geometry >, Rest ... >::update_jac< S >", "a37773.html", null ],
    [ "gdl::functors::update_jac< Geometry, S >", "a37465.html", null ],
    [ "gdl::aggregator_type_tuple< bd_assembly< Boundary >, Rest ... >::upwind< Flux >", "a37857.html", null ],
    [ "gdl::functors::upwind", "a37585.html", null ],
    [ "gdl::functors::vecvec< Dim, Operator >", "a37629.html", null ],
    [ "gdl::functors::vecvec< 4, Operator >", "a37633.html", null ],
    [ "gdl::functors::vecvec< 5, Operator >", "a37637.html", null ],
    [ "gdl::zero< T >", "a37665.html", null ],
    [ "basis_function_storage_t", "a38363.html", null ],
    [ "basis_function_storage_t_info", "a38339.html", null ],
    [ "double", "a38379.html", null ],
    [ "grad_storage_t", "a38355.html", null ],
    [ "grad_storage_t_info", "a38331.html", null ],
    [ "storage_info_t< gt::pair< discretization< GeoMap, Cubature >, static_int< __COUNTER__ > >, layout3_t >", "a38323.html", null ],
    [ "storage_t< cub_points_storage_t_info >", "a38343.html", null ],
    [ "storage_t< weights_storage_t_info >", "a38347.html", null ],
    [ "uint_t", "a38319.html", null ]
];